// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/nuomizi-fw/stargazer/service"
)

// Ensure, that Aria2ServiceMock does implement service.Aria2Service.
// If this is not the case, regenerate this file with moq.
var _ service.Aria2Service = &Aria2ServiceMock{}

// Aria2ServiceMock is a mock implementation of service.Aria2Service.
//
//	func TestSomethingThatUsesAria2Service(t *testing.T) {
//
//		// make and configure a mocked service.Aria2Service
//		mockedAria2Service := &Aria2ServiceMock{
//		}
//
//		// use mockedAria2Service in code that requires service.Aria2Service
//		// and then make assertions.
//
//	}
type Aria2ServiceMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
