// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/nuomizi-fw/stargazer/service"
)

// Ensure, that MangaServiceMock does implement service.MangaService.
// If this is not the case, regenerate this file with moq.
var _ service.MangaService = &MangaServiceMock{}

// MangaServiceMock is a mock implementation of service.MangaService.
//
//	func TestSomethingThatUsesMangaService(t *testing.T) {
//
//		// make and configure a mocked service.MangaService
//		mockedMangaService := &MangaServiceMock{
//		}
//
//		// use mockedMangaService in code that requires service.MangaService
//		// and then make assertions.
//
//	}
type MangaServiceMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
