// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/nuomizi-fw/stargazer/service"
)

// Ensure, that MusicServiceMock does implement service.MusicService.
// If this is not the case, regenerate this file with moq.
var _ service.MusicService = &MusicServiceMock{}

// MusicServiceMock is a mock implementation of service.MusicService.
//
//	func TestSomethingThatUsesMusicService(t *testing.T) {
//
//		// make and configure a mocked service.MusicService
//		mockedMusicService := &MusicServiceMock{
//		}
//
//		// use mockedMusicService in code that requires service.MusicService
//		// and then make assertions.
//
//	}
type MusicServiceMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
