// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/nuomizi-fw/stargazer/service"
)

// Ensure, that NovelServiceMock does implement service.NovelService.
// If this is not the case, regenerate this file with moq.
var _ service.NovelService = &NovelServiceMock{}

// NovelServiceMock is a mock implementation of service.NovelService.
//
//	func TestSomethingThatUsesNovelService(t *testing.T) {
//
//		// make and configure a mocked service.NovelService
//		mockedNovelService := &NovelServiceMock{
//		}
//
//		// use mockedNovelService in code that requires service.NovelService
//		// and then make assertions.
//
//	}
type NovelServiceMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
