// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/nuomizi-fw/stargazer/service"
)

// Ensure, that RssServiceMock does implement service.RssService.
// If this is not the case, regenerate this file with moq.
var _ service.RssService = &RssServiceMock{}

// RssServiceMock is a mock implementation of service.RssService.
//
//	func TestSomethingThatUsesRssService(t *testing.T) {
//
//		// make and configure a mocked service.RssService
//		mockedRssService := &RssServiceMock{
//		}
//
//		// use mockedRssService in code that requires service.RssService
//		// and then make assertions.
//
//	}
type RssServiceMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
