// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/nuomizi-fw/stargazer/service"
)

// Ensure, that SearchServiceMock does implement service.SearchService.
// If this is not the case, regenerate this file with moq.
var _ service.SearchService = &SearchServiceMock{}

// SearchServiceMock is a mock implementation of service.SearchService.
//
//	func TestSomethingThatUsesSearchService(t *testing.T) {
//
//		// make and configure a mocked service.SearchService
//		mockedSearchService := &SearchServiceMock{
//		}
//
//		// use mockedSearchService in code that requires service.SearchService
//		// and then make assertions.
//
//	}
type SearchServiceMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
