// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/nuomizi-fw/stargazer/service"
)

// Ensure, that TransmissionServiceMock does implement service.TransmissionService.
// If this is not the case, regenerate this file with moq.
var _ service.TransmissionService = &TransmissionServiceMock{}

// TransmissionServiceMock is a mock implementation of service.TransmissionService.
//
//	func TestSomethingThatUsesTransmissionService(t *testing.T) {
//
//		// make and configure a mocked service.TransmissionService
//		mockedTransmissionService := &TransmissionServiceMock{
//		}
//
//		// use mockedTransmissionService in code that requires service.TransmissionService
//		// and then make assertions.
//
//	}
type TransmissionServiceMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
