// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuomizi-fw/stargazer/ent/bangumi"
	"github.com/nuomizi-fw/stargazer/ent/castmember"
	"github.com/nuomizi-fw/stargazer/ent/predicate"
	"github.com/nuomizi-fw/stargazer/ent/season"
)

// BangumiQuery is the builder for querying Bangumi entities.
type BangumiQuery struct {
	config
	ctx             *QueryContext
	order           []bangumi.OrderOption
	inters          []Interceptor
	predicates      []predicate.Bangumi
	withSeasons     *SeasonQuery
	withCastMembers *CastMemberQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BangumiQuery builder.
func (bq *BangumiQuery) Where(ps ...predicate.Bangumi) *BangumiQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BangumiQuery) Limit(limit int) *BangumiQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BangumiQuery) Offset(offset int) *BangumiQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BangumiQuery) Unique(unique bool) *BangumiQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BangumiQuery) Order(o ...bangumi.OrderOption) *BangumiQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QuerySeasons chains the current query on the "seasons" edge.
func (bq *BangumiQuery) QuerySeasons() *SeasonQuery {
	query := (&SeasonClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bangumi.Table, bangumi.FieldID, selector),
			sqlgraph.To(season.Table, season.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bangumi.SeasonsTable, bangumi.SeasonsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCastMembers chains the current query on the "cast_members" edge.
func (bq *BangumiQuery) QueryCastMembers() *CastMemberQuery {
	query := (&CastMemberClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bangumi.Table, bangumi.FieldID, selector),
			sqlgraph.To(castmember.Table, castmember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bangumi.CastMembersTable, bangumi.CastMembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Bangumi entity from the query.
// Returns a *NotFoundError when no Bangumi was found.
func (bq *BangumiQuery) First(ctx context.Context) (*Bangumi, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bangumi.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BangumiQuery) FirstX(ctx context.Context) *Bangumi {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Bangumi ID from the query.
// Returns a *NotFoundError when no Bangumi ID was found.
func (bq *BangumiQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bangumi.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BangumiQuery) FirstIDX(ctx context.Context) int {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Bangumi entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Bangumi entity is found.
// Returns a *NotFoundError when no Bangumi entities are found.
func (bq *BangumiQuery) Only(ctx context.Context) (*Bangumi, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bangumi.Label}
	default:
		return nil, &NotSingularError{bangumi.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BangumiQuery) OnlyX(ctx context.Context) *Bangumi {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Bangumi ID in the query.
// Returns a *NotSingularError when more than one Bangumi ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BangumiQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bangumi.Label}
	default:
		err = &NotSingularError{bangumi.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BangumiQuery) OnlyIDX(ctx context.Context) int {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Bangumis.
func (bq *BangumiQuery) All(ctx context.Context) ([]*Bangumi, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryAll)
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Bangumi, *BangumiQuery]()
	return withInterceptors[[]*Bangumi](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BangumiQuery) AllX(ctx context.Context) []*Bangumi {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Bangumi IDs.
func (bq *BangumiQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryIDs)
	if err = bq.Select(bangumi.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BangumiQuery) IDsX(ctx context.Context) []int {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BangumiQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryCount)
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BangumiQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BangumiQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BangumiQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryExist)
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BangumiQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BangumiQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BangumiQuery) Clone() *BangumiQuery {
	if bq == nil {
		return nil
	}
	return &BangumiQuery{
		config:          bq.config,
		ctx:             bq.ctx.Clone(),
		order:           append([]bangumi.OrderOption{}, bq.order...),
		inters:          append([]Interceptor{}, bq.inters...),
		predicates:      append([]predicate.Bangumi{}, bq.predicates...),
		withSeasons:     bq.withSeasons.Clone(),
		withCastMembers: bq.withCastMembers.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithSeasons tells the query-builder to eager-load the nodes that are connected to
// the "seasons" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BangumiQuery) WithSeasons(opts ...func(*SeasonQuery)) *BangumiQuery {
	query := (&SeasonClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withSeasons = query
	return bq
}

// WithCastMembers tells the query-builder to eager-load the nodes that are connected to
// the "cast_members" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BangumiQuery) WithCastMembers(opts ...func(*CastMemberQuery)) *BangumiQuery {
	query := (&CastMemberClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withCastMembers = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Bangumi.Query().
//		GroupBy(bangumi.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BangumiQuery) GroupBy(field string, fields ...string) *BangumiGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BangumiGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = bangumi.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Bangumi.Query().
//		Select(bangumi.FieldTitle).
//		Scan(ctx, &v)
func (bq *BangumiQuery) Select(fields ...string) *BangumiSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BangumiSelect{BangumiQuery: bq}
	sbuild.label = bangumi.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BangumiSelect configured with the given aggregations.
func (bq *BangumiQuery) Aggregate(fns ...AggregateFunc) *BangumiSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BangumiQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !bangumi.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BangumiQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Bangumi, error) {
	var (
		nodes       = []*Bangumi{}
		_spec       = bq.querySpec()
		loadedTypes = [2]bool{
			bq.withSeasons != nil,
			bq.withCastMembers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Bangumi).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Bangumi{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withSeasons; query != nil {
		if err := bq.loadSeasons(ctx, query, nodes,
			func(n *Bangumi) { n.Edges.Seasons = []*Season{} },
			func(n *Bangumi, e *Season) { n.Edges.Seasons = append(n.Edges.Seasons, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withCastMembers; query != nil {
		if err := bq.loadCastMembers(ctx, query, nodes,
			func(n *Bangumi) { n.Edges.CastMembers = []*CastMember{} },
			func(n *Bangumi, e *CastMember) { n.Edges.CastMembers = append(n.Edges.CastMembers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BangumiQuery) loadSeasons(ctx context.Context, query *SeasonQuery, nodes []*Bangumi, init func(*Bangumi), assign func(*Bangumi, *Season)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Bangumi)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(season.FieldBangumiID)
	}
	query.Where(predicate.Season(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(bangumi.SeasonsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BangumiID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "bangumi_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BangumiQuery) loadCastMembers(ctx context.Context, query *CastMemberQuery, nodes []*Bangumi, init func(*Bangumi), assign func(*Bangumi, *CastMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Bangumi)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CastMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(bangumi.CastMembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.bangumi_cast_members
		if fk == nil {
			return fmt.Errorf(`foreign-key "bangumi_cast_members" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "bangumi_cast_members" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (bq *BangumiQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BangumiQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bangumi.Table, bangumi.Columns, sqlgraph.NewFieldSpec(bangumi.FieldID, field.TypeInt))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bangumi.FieldID)
		for i := range fields {
			if fields[i] != bangumi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BangumiQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(bangumi.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = bangumi.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BangumiGroupBy is the group-by builder for Bangumi entities.
type BangumiGroupBy struct {
	selector
	build *BangumiQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BangumiGroupBy) Aggregate(fns ...AggregateFunc) *BangumiGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BangumiGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, ent.OpQueryGroupBy)
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BangumiQuery, *BangumiGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BangumiGroupBy) sqlScan(ctx context.Context, root *BangumiQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BangumiSelect is the builder for selecting fields of Bangumi entities.
type BangumiSelect struct {
	*BangumiQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BangumiSelect) Aggregate(fns ...AggregateFunc) *BangumiSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BangumiSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, ent.OpQuerySelect)
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BangumiQuery, *BangumiSelect](ctx, bs.BangumiQuery, bs, bs.inters, v)
}

func (bs *BangumiSelect) sqlScan(ctx context.Context, root *BangumiQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
