// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuomizi-fw/stargazer/ent/castmember"
	"github.com/nuomizi-fw/stargazer/ent/predicate"
	"github.com/nuomizi-fw/stargazer/ent/season"
)

// CastMemberQuery is the builder for querying CastMember entities.
type CastMemberQuery struct {
	config
	ctx        *QueryContext
	order      []castmember.OrderOption
	inters     []Interceptor
	predicates []predicate.CastMember
	withSeason *SeasonQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CastMemberQuery builder.
func (cmq *CastMemberQuery) Where(ps ...predicate.CastMember) *CastMemberQuery {
	cmq.predicates = append(cmq.predicates, ps...)
	return cmq
}

// Limit the number of records to be returned by this query.
func (cmq *CastMemberQuery) Limit(limit int) *CastMemberQuery {
	cmq.ctx.Limit = &limit
	return cmq
}

// Offset to start from.
func (cmq *CastMemberQuery) Offset(offset int) *CastMemberQuery {
	cmq.ctx.Offset = &offset
	return cmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cmq *CastMemberQuery) Unique(unique bool) *CastMemberQuery {
	cmq.ctx.Unique = &unique
	return cmq
}

// Order specifies how the records should be ordered.
func (cmq *CastMemberQuery) Order(o ...castmember.OrderOption) *CastMemberQuery {
	cmq.order = append(cmq.order, o...)
	return cmq
}

// QuerySeason chains the current query on the "season" edge.
func (cmq *CastMemberQuery) QuerySeason() *SeasonQuery {
	query := (&SeasonClient{config: cmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(castmember.Table, castmember.FieldID, selector),
			sqlgraph.To(season.Table, season.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, castmember.SeasonTable, castmember.SeasonColumn),
		)
		fromU = sqlgraph.SetNeighbors(cmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CastMember entity from the query.
// Returns a *NotFoundError when no CastMember was found.
func (cmq *CastMemberQuery) First(ctx context.Context) (*CastMember, error) {
	nodes, err := cmq.Limit(1).All(setContextOp(ctx, cmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{castmember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cmq *CastMemberQuery) FirstX(ctx context.Context) *CastMember {
	node, err := cmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CastMember ID from the query.
// Returns a *NotFoundError when no CastMember ID was found.
func (cmq *CastMemberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cmq.Limit(1).IDs(setContextOp(ctx, cmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{castmember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cmq *CastMemberQuery) FirstIDX(ctx context.Context) int {
	id, err := cmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CastMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CastMember entity is found.
// Returns a *NotFoundError when no CastMember entities are found.
func (cmq *CastMemberQuery) Only(ctx context.Context) (*CastMember, error) {
	nodes, err := cmq.Limit(2).All(setContextOp(ctx, cmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{castmember.Label}
	default:
		return nil, &NotSingularError{castmember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cmq *CastMemberQuery) OnlyX(ctx context.Context) *CastMember {
	node, err := cmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CastMember ID in the query.
// Returns a *NotSingularError when more than one CastMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (cmq *CastMemberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cmq.Limit(2).IDs(setContextOp(ctx, cmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{castmember.Label}
	default:
		err = &NotSingularError{castmember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cmq *CastMemberQuery) OnlyIDX(ctx context.Context) int {
	id, err := cmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CastMembers.
func (cmq *CastMemberQuery) All(ctx context.Context) ([]*CastMember, error) {
	ctx = setContextOp(ctx, cmq.ctx, ent.OpQueryAll)
	if err := cmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CastMember, *CastMemberQuery]()
	return withInterceptors[[]*CastMember](ctx, cmq, qr, cmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cmq *CastMemberQuery) AllX(ctx context.Context) []*CastMember {
	nodes, err := cmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CastMember IDs.
func (cmq *CastMemberQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cmq.ctx.Unique == nil && cmq.path != nil {
		cmq.Unique(true)
	}
	ctx = setContextOp(ctx, cmq.ctx, ent.OpQueryIDs)
	if err = cmq.Select(castmember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cmq *CastMemberQuery) IDsX(ctx context.Context) []int {
	ids, err := cmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cmq *CastMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cmq.ctx, ent.OpQueryCount)
	if err := cmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cmq, querierCount[*CastMemberQuery](), cmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cmq *CastMemberQuery) CountX(ctx context.Context) int {
	count, err := cmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cmq *CastMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cmq.ctx, ent.OpQueryExist)
	switch _, err := cmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cmq *CastMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := cmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CastMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cmq *CastMemberQuery) Clone() *CastMemberQuery {
	if cmq == nil {
		return nil
	}
	return &CastMemberQuery{
		config:     cmq.config,
		ctx:        cmq.ctx.Clone(),
		order:      append([]castmember.OrderOption{}, cmq.order...),
		inters:     append([]Interceptor{}, cmq.inters...),
		predicates: append([]predicate.CastMember{}, cmq.predicates...),
		withSeason: cmq.withSeason.Clone(),
		// clone intermediate query.
		sql:  cmq.sql.Clone(),
		path: cmq.path,
	}
}

// WithSeason tells the query-builder to eager-load the nodes that are connected to
// the "season" edge. The optional arguments are used to configure the query builder of the edge.
func (cmq *CastMemberQuery) WithSeason(opts ...func(*SeasonQuery)) *CastMemberQuery {
	query := (&SeasonClient{config: cmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cmq.withSeason = query
	return cmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CastMember.Query().
//		GroupBy(castmember.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cmq *CastMemberQuery) GroupBy(field string, fields ...string) *CastMemberGroupBy {
	cmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CastMemberGroupBy{build: cmq}
	grbuild.flds = &cmq.ctx.Fields
	grbuild.label = castmember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.CastMember.Query().
//		Select(castmember.FieldName).
//		Scan(ctx, &v)
func (cmq *CastMemberQuery) Select(fields ...string) *CastMemberSelect {
	cmq.ctx.Fields = append(cmq.ctx.Fields, fields...)
	sbuild := &CastMemberSelect{CastMemberQuery: cmq}
	sbuild.label = castmember.Label
	sbuild.flds, sbuild.scan = &cmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CastMemberSelect configured with the given aggregations.
func (cmq *CastMemberQuery) Aggregate(fns ...AggregateFunc) *CastMemberSelect {
	return cmq.Select().Aggregate(fns...)
}

func (cmq *CastMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cmq); err != nil {
				return err
			}
		}
	}
	for _, f := range cmq.ctx.Fields {
		if !castmember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cmq.path != nil {
		prev, err := cmq.path(ctx)
		if err != nil {
			return err
		}
		cmq.sql = prev
	}
	return nil
}

func (cmq *CastMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CastMember, error) {
	var (
		nodes       = []*CastMember{}
		withFKs     = cmq.withFKs
		_spec       = cmq.querySpec()
		loadedTypes = [1]bool{
			cmq.withSeason != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, castmember.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CastMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CastMember{config: cmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cmq.withSeason; query != nil {
		if err := cmq.loadSeason(ctx, query, nodes, nil,
			func(n *CastMember, e *Season) { n.Edges.Season = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cmq *CastMemberQuery) loadSeason(ctx context.Context, query *SeasonQuery, nodes []*CastMember, init func(*CastMember), assign func(*CastMember, *Season)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CastMember)
	for i := range nodes {
		fk := nodes[i].SeasonID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(season.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "season_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cmq *CastMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cmq.querySpec()
	_spec.Node.Columns = cmq.ctx.Fields
	if len(cmq.ctx.Fields) > 0 {
		_spec.Unique = cmq.ctx.Unique != nil && *cmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cmq.driver, _spec)
}

func (cmq *CastMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(castmember.Table, castmember.Columns, sqlgraph.NewFieldSpec(castmember.FieldID, field.TypeInt))
	_spec.From = cmq.sql
	if unique := cmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cmq.path != nil {
		_spec.Unique = true
	}
	if fields := cmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, castmember.FieldID)
		for i := range fields {
			if fields[i] != castmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if cmq.withSeason != nil {
			_spec.Node.AddColumnOnce(castmember.FieldSeasonID)
		}
	}
	if ps := cmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cmq *CastMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cmq.driver.Dialect())
	t1 := builder.Table(castmember.Table)
	columns := cmq.ctx.Fields
	if len(columns) == 0 {
		columns = castmember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cmq.sql != nil {
		selector = cmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cmq.ctx.Unique != nil && *cmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cmq.predicates {
		p(selector)
	}
	for _, p := range cmq.order {
		p(selector)
	}
	if offset := cmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CastMemberGroupBy is the group-by builder for CastMember entities.
type CastMemberGroupBy struct {
	selector
	build *CastMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cmgb *CastMemberGroupBy) Aggregate(fns ...AggregateFunc) *CastMemberGroupBy {
	cmgb.fns = append(cmgb.fns, fns...)
	return cmgb
}

// Scan applies the selector query and scans the result into the given value.
func (cmgb *CastMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cmgb.build.ctx, ent.OpQueryGroupBy)
	if err := cmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CastMemberQuery, *CastMemberGroupBy](ctx, cmgb.build, cmgb, cmgb.build.inters, v)
}

func (cmgb *CastMemberGroupBy) sqlScan(ctx context.Context, root *CastMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cmgb.fns))
	for _, fn := range cmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cmgb.flds)+len(cmgb.fns))
		for _, f := range *cmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CastMemberSelect is the builder for selecting fields of CastMember entities.
type CastMemberSelect struct {
	*CastMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cms *CastMemberSelect) Aggregate(fns ...AggregateFunc) *CastMemberSelect {
	cms.fns = append(cms.fns, fns...)
	return cms
}

// Scan applies the selector query and scans the result into the given value.
func (cms *CastMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cms.ctx, ent.OpQuerySelect)
	if err := cms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CastMemberQuery, *CastMemberSelect](ctx, cms.CastMemberQuery, cms, cms.inters, v)
}

func (cms *CastMemberSelect) sqlScan(ctx context.Context, root *CastMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cms.fns))
	for _, fn := range cms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
