// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuomizi-fw/stargazer/ent/castmember"
	"github.com/nuomizi-fw/stargazer/ent/episode"
	"github.com/nuomizi-fw/stargazer/ent/predicate"
	"github.com/nuomizi-fw/stargazer/ent/season"
)

// EpisodeUpdate is the builder for updating Episode entities.
type EpisodeUpdate struct {
	config
	hooks    []Hook
	mutation *EpisodeMutation
}

// Where appends a list predicates to the EpisodeUpdate builder.
func (eu *EpisodeUpdate) Where(ps ...predicate.Episode) *EpisodeUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetEpisodeNumber sets the "episode_number" field.
func (eu *EpisodeUpdate) SetEpisodeNumber(i int) *EpisodeUpdate {
	eu.mutation.ResetEpisodeNumber()
	eu.mutation.SetEpisodeNumber(i)
	return eu
}

// SetNillableEpisodeNumber sets the "episode_number" field if the given value is not nil.
func (eu *EpisodeUpdate) SetNillableEpisodeNumber(i *int) *EpisodeUpdate {
	if i != nil {
		eu.SetEpisodeNumber(*i)
	}
	return eu
}

// AddEpisodeNumber adds i to the "episode_number" field.
func (eu *EpisodeUpdate) AddEpisodeNumber(i int) *EpisodeUpdate {
	eu.mutation.AddEpisodeNumber(i)
	return eu
}

// SetTitle sets the "title" field.
func (eu *EpisodeUpdate) SetTitle(s string) *EpisodeUpdate {
	eu.mutation.SetTitle(s)
	return eu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (eu *EpisodeUpdate) SetNillableTitle(s *string) *EpisodeUpdate {
	if s != nil {
		eu.SetTitle(*s)
	}
	return eu
}

// SetOverview sets the "overview" field.
func (eu *EpisodeUpdate) SetOverview(s string) *EpisodeUpdate {
	eu.mutation.SetOverview(s)
	return eu
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (eu *EpisodeUpdate) SetNillableOverview(s *string) *EpisodeUpdate {
	if s != nil {
		eu.SetOverview(*s)
	}
	return eu
}

// ClearOverview clears the value of the "overview" field.
func (eu *EpisodeUpdate) ClearOverview() *EpisodeUpdate {
	eu.mutation.ClearOverview()
	return eu
}

// SetAirDate sets the "air_date" field.
func (eu *EpisodeUpdate) SetAirDate(t time.Time) *EpisodeUpdate {
	eu.mutation.SetAirDate(t)
	return eu
}

// SetNillableAirDate sets the "air_date" field if the given value is not nil.
func (eu *EpisodeUpdate) SetNillableAirDate(t *time.Time) *EpisodeUpdate {
	if t != nil {
		eu.SetAirDate(*t)
	}
	return eu
}

// ClearAirDate clears the value of the "air_date" field.
func (eu *EpisodeUpdate) ClearAirDate() *EpisodeUpdate {
	eu.mutation.ClearAirDate()
	return eu
}

// SetSeasonID sets the "season_id" field.
func (eu *EpisodeUpdate) SetSeasonID(i int) *EpisodeUpdate {
	eu.mutation.SetSeasonID(i)
	return eu
}

// SetNillableSeasonID sets the "season_id" field if the given value is not nil.
func (eu *EpisodeUpdate) SetNillableSeasonID(i *int) *EpisodeUpdate {
	if i != nil {
		eu.SetSeasonID(*i)
	}
	return eu
}

// ClearSeasonID clears the value of the "season_id" field.
func (eu *EpisodeUpdate) ClearSeasonID() *EpisodeUpdate {
	eu.mutation.ClearSeasonID()
	return eu
}

// SetSeason sets the "season" edge to the Season entity.
func (eu *EpisodeUpdate) SetSeason(s *Season) *EpisodeUpdate {
	return eu.SetSeasonID(s.ID)
}

// AddCastMemberIDs adds the "cast_members" edge to the CastMember entity by IDs.
func (eu *EpisodeUpdate) AddCastMemberIDs(ids ...int) *EpisodeUpdate {
	eu.mutation.AddCastMemberIDs(ids...)
	return eu
}

// AddCastMembers adds the "cast_members" edges to the CastMember entity.
func (eu *EpisodeUpdate) AddCastMembers(c ...*CastMember) *EpisodeUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return eu.AddCastMemberIDs(ids...)
}

// Mutation returns the EpisodeMutation object of the builder.
func (eu *EpisodeUpdate) Mutation() *EpisodeMutation {
	return eu.mutation
}

// ClearSeason clears the "season" edge to the Season entity.
func (eu *EpisodeUpdate) ClearSeason() *EpisodeUpdate {
	eu.mutation.ClearSeason()
	return eu
}

// ClearCastMembers clears all "cast_members" edges to the CastMember entity.
func (eu *EpisodeUpdate) ClearCastMembers() *EpisodeUpdate {
	eu.mutation.ClearCastMembers()
	return eu
}

// RemoveCastMemberIDs removes the "cast_members" edge to CastMember entities by IDs.
func (eu *EpisodeUpdate) RemoveCastMemberIDs(ids ...int) *EpisodeUpdate {
	eu.mutation.RemoveCastMemberIDs(ids...)
	return eu
}

// RemoveCastMembers removes "cast_members" edges to CastMember entities.
func (eu *EpisodeUpdate) RemoveCastMembers(c ...*CastMember) *EpisodeUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return eu.RemoveCastMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EpisodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EpisodeUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EpisodeUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EpisodeUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EpisodeUpdate) check() error {
	if v, ok := eu.mutation.EpisodeNumber(); ok {
		if err := episode.EpisodeNumberValidator(v); err != nil {
			return &ValidationError{Name: "episode_number", err: fmt.Errorf(`ent: validator failed for field "Episode.episode_number": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Title(); ok {
		if err := episode.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Episode.title": %w`, err)}
		}
	}
	if v, ok := eu.mutation.SeasonID(); ok {
		if err := episode.SeasonIDValidator(v); err != nil {
			return &ValidationError{Name: "season_id", err: fmt.Errorf(`ent: validator failed for field "Episode.season_id": %w`, err)}
		}
	}
	return nil
}

func (eu *EpisodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(episode.Table, episode.Columns, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.EpisodeNumber(); ok {
		_spec.SetField(episode.FieldEpisodeNumber, field.TypeInt, value)
	}
	if value, ok := eu.mutation.AddedEpisodeNumber(); ok {
		_spec.AddField(episode.FieldEpisodeNumber, field.TypeInt, value)
	}
	if value, ok := eu.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
	}
	if value, ok := eu.mutation.Overview(); ok {
		_spec.SetField(episode.FieldOverview, field.TypeString, value)
	}
	if eu.mutation.OverviewCleared() {
		_spec.ClearField(episode.FieldOverview, field.TypeString)
	}
	if value, ok := eu.mutation.AirDate(); ok {
		_spec.SetField(episode.FieldAirDate, field.TypeTime, value)
	}
	if eu.mutation.AirDateCleared() {
		_spec.ClearField(episode.FieldAirDate, field.TypeTime)
	}
	if eu.mutation.SeasonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.SeasonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.CastMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.CastMembersTable,
			Columns: []string{episode.CastMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(castmember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.RemovedCastMembersIDs(); len(nodes) > 0 && !eu.mutation.CastMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.CastMembersTable,
			Columns: []string{episode.CastMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(castmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.CastMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.CastMembersTable,
			Columns: []string{episode.CastMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(castmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{episode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EpisodeUpdateOne is the builder for updating a single Episode entity.
type EpisodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EpisodeMutation
}

// SetEpisodeNumber sets the "episode_number" field.
func (euo *EpisodeUpdateOne) SetEpisodeNumber(i int) *EpisodeUpdateOne {
	euo.mutation.ResetEpisodeNumber()
	euo.mutation.SetEpisodeNumber(i)
	return euo
}

// SetNillableEpisodeNumber sets the "episode_number" field if the given value is not nil.
func (euo *EpisodeUpdateOne) SetNillableEpisodeNumber(i *int) *EpisodeUpdateOne {
	if i != nil {
		euo.SetEpisodeNumber(*i)
	}
	return euo
}

// AddEpisodeNumber adds i to the "episode_number" field.
func (euo *EpisodeUpdateOne) AddEpisodeNumber(i int) *EpisodeUpdateOne {
	euo.mutation.AddEpisodeNumber(i)
	return euo
}

// SetTitle sets the "title" field.
func (euo *EpisodeUpdateOne) SetTitle(s string) *EpisodeUpdateOne {
	euo.mutation.SetTitle(s)
	return euo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (euo *EpisodeUpdateOne) SetNillableTitle(s *string) *EpisodeUpdateOne {
	if s != nil {
		euo.SetTitle(*s)
	}
	return euo
}

// SetOverview sets the "overview" field.
func (euo *EpisodeUpdateOne) SetOverview(s string) *EpisodeUpdateOne {
	euo.mutation.SetOverview(s)
	return euo
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (euo *EpisodeUpdateOne) SetNillableOverview(s *string) *EpisodeUpdateOne {
	if s != nil {
		euo.SetOverview(*s)
	}
	return euo
}

// ClearOverview clears the value of the "overview" field.
func (euo *EpisodeUpdateOne) ClearOverview() *EpisodeUpdateOne {
	euo.mutation.ClearOverview()
	return euo
}

// SetAirDate sets the "air_date" field.
func (euo *EpisodeUpdateOne) SetAirDate(t time.Time) *EpisodeUpdateOne {
	euo.mutation.SetAirDate(t)
	return euo
}

// SetNillableAirDate sets the "air_date" field if the given value is not nil.
func (euo *EpisodeUpdateOne) SetNillableAirDate(t *time.Time) *EpisodeUpdateOne {
	if t != nil {
		euo.SetAirDate(*t)
	}
	return euo
}

// ClearAirDate clears the value of the "air_date" field.
func (euo *EpisodeUpdateOne) ClearAirDate() *EpisodeUpdateOne {
	euo.mutation.ClearAirDate()
	return euo
}

// SetSeasonID sets the "season_id" field.
func (euo *EpisodeUpdateOne) SetSeasonID(i int) *EpisodeUpdateOne {
	euo.mutation.SetSeasonID(i)
	return euo
}

// SetNillableSeasonID sets the "season_id" field if the given value is not nil.
func (euo *EpisodeUpdateOne) SetNillableSeasonID(i *int) *EpisodeUpdateOne {
	if i != nil {
		euo.SetSeasonID(*i)
	}
	return euo
}

// ClearSeasonID clears the value of the "season_id" field.
func (euo *EpisodeUpdateOne) ClearSeasonID() *EpisodeUpdateOne {
	euo.mutation.ClearSeasonID()
	return euo
}

// SetSeason sets the "season" edge to the Season entity.
func (euo *EpisodeUpdateOne) SetSeason(s *Season) *EpisodeUpdateOne {
	return euo.SetSeasonID(s.ID)
}

// AddCastMemberIDs adds the "cast_members" edge to the CastMember entity by IDs.
func (euo *EpisodeUpdateOne) AddCastMemberIDs(ids ...int) *EpisodeUpdateOne {
	euo.mutation.AddCastMemberIDs(ids...)
	return euo
}

// AddCastMembers adds the "cast_members" edges to the CastMember entity.
func (euo *EpisodeUpdateOne) AddCastMembers(c ...*CastMember) *EpisodeUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return euo.AddCastMemberIDs(ids...)
}

// Mutation returns the EpisodeMutation object of the builder.
func (euo *EpisodeUpdateOne) Mutation() *EpisodeMutation {
	return euo.mutation
}

// ClearSeason clears the "season" edge to the Season entity.
func (euo *EpisodeUpdateOne) ClearSeason() *EpisodeUpdateOne {
	euo.mutation.ClearSeason()
	return euo
}

// ClearCastMembers clears all "cast_members" edges to the CastMember entity.
func (euo *EpisodeUpdateOne) ClearCastMembers() *EpisodeUpdateOne {
	euo.mutation.ClearCastMembers()
	return euo
}

// RemoveCastMemberIDs removes the "cast_members" edge to CastMember entities by IDs.
func (euo *EpisodeUpdateOne) RemoveCastMemberIDs(ids ...int) *EpisodeUpdateOne {
	euo.mutation.RemoveCastMemberIDs(ids...)
	return euo
}

// RemoveCastMembers removes "cast_members" edges to CastMember entities.
func (euo *EpisodeUpdateOne) RemoveCastMembers(c ...*CastMember) *EpisodeUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return euo.RemoveCastMemberIDs(ids...)
}

// Where appends a list predicates to the EpisodeUpdate builder.
func (euo *EpisodeUpdateOne) Where(ps ...predicate.Episode) *EpisodeUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EpisodeUpdateOne) Select(field string, fields ...string) *EpisodeUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Episode entity.
func (euo *EpisodeUpdateOne) Save(ctx context.Context) (*Episode, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EpisodeUpdateOne) SaveX(ctx context.Context) *Episode {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EpisodeUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EpisodeUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EpisodeUpdateOne) check() error {
	if v, ok := euo.mutation.EpisodeNumber(); ok {
		if err := episode.EpisodeNumberValidator(v); err != nil {
			return &ValidationError{Name: "episode_number", err: fmt.Errorf(`ent: validator failed for field "Episode.episode_number": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Title(); ok {
		if err := episode.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Episode.title": %w`, err)}
		}
	}
	if v, ok := euo.mutation.SeasonID(); ok {
		if err := episode.SeasonIDValidator(v); err != nil {
			return &ValidationError{Name: "season_id", err: fmt.Errorf(`ent: validator failed for field "Episode.season_id": %w`, err)}
		}
	}
	return nil
}

func (euo *EpisodeUpdateOne) sqlSave(ctx context.Context) (_node *Episode, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(episode.Table, episode.Columns, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Episode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, episode.FieldID)
		for _, f := range fields {
			if !episode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != episode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.EpisodeNumber(); ok {
		_spec.SetField(episode.FieldEpisodeNumber, field.TypeInt, value)
	}
	if value, ok := euo.mutation.AddedEpisodeNumber(); ok {
		_spec.AddField(episode.FieldEpisodeNumber, field.TypeInt, value)
	}
	if value, ok := euo.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
	}
	if value, ok := euo.mutation.Overview(); ok {
		_spec.SetField(episode.FieldOverview, field.TypeString, value)
	}
	if euo.mutation.OverviewCleared() {
		_spec.ClearField(episode.FieldOverview, field.TypeString)
	}
	if value, ok := euo.mutation.AirDate(); ok {
		_spec.SetField(episode.FieldAirDate, field.TypeTime, value)
	}
	if euo.mutation.AirDateCleared() {
		_spec.ClearField(episode.FieldAirDate, field.TypeTime)
	}
	if euo.mutation.SeasonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.SeasonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.CastMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.CastMembersTable,
			Columns: []string{episode.CastMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(castmember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.RemovedCastMembersIDs(); len(nodes) > 0 && !euo.mutation.CastMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.CastMembersTable,
			Columns: []string{episode.CastMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(castmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.CastMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.CastMembersTable,
			Columns: []string{episode.CastMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(castmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Episode{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{episode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
