// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuomizi-fw/stargazer/ent/bangumi"
	"github.com/nuomizi-fw/stargazer/ent/castmember"
	"github.com/nuomizi-fw/stargazer/ent/episode"
	"github.com/nuomizi-fw/stargazer/ent/predicate"
	"github.com/nuomizi-fw/stargazer/ent/season"
)

// SeasonQuery is the builder for querying Season entities.
type SeasonQuery struct {
	config
	ctx             *QueryContext
	order           []season.OrderOption
	inters          []Interceptor
	predicates      []predicate.Season
	withBangumi     *BangumiQuery
	withEpisodes    *EpisodeQuery
	withCastMembers *CastMemberQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SeasonQuery builder.
func (sq *SeasonQuery) Where(ps ...predicate.Season) *SeasonQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SeasonQuery) Limit(limit int) *SeasonQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SeasonQuery) Offset(offset int) *SeasonQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SeasonQuery) Unique(unique bool) *SeasonQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SeasonQuery) Order(o ...season.OrderOption) *SeasonQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryBangumi chains the current query on the "bangumi" edge.
func (sq *SeasonQuery) QueryBangumi() *BangumiQuery {
	query := (&BangumiClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(season.Table, season.FieldID, selector),
			sqlgraph.To(bangumi.Table, bangumi.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, season.BangumiTable, season.BangumiColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEpisodes chains the current query on the "episodes" edge.
func (sq *SeasonQuery) QueryEpisodes() *EpisodeQuery {
	query := (&EpisodeClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(season.Table, season.FieldID, selector),
			sqlgraph.To(episode.Table, episode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, season.EpisodesTable, season.EpisodesColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCastMembers chains the current query on the "cast_members" edge.
func (sq *SeasonQuery) QueryCastMembers() *CastMemberQuery {
	query := (&CastMemberClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(season.Table, season.FieldID, selector),
			sqlgraph.To(castmember.Table, castmember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, season.CastMembersTable, season.CastMembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Season entity from the query.
// Returns a *NotFoundError when no Season was found.
func (sq *SeasonQuery) First(ctx context.Context) (*Season, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{season.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SeasonQuery) FirstX(ctx context.Context) *Season {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Season ID from the query.
// Returns a *NotFoundError when no Season ID was found.
func (sq *SeasonQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{season.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SeasonQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Season entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Season entity is found.
// Returns a *NotFoundError when no Season entities are found.
func (sq *SeasonQuery) Only(ctx context.Context) (*Season, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{season.Label}
	default:
		return nil, &NotSingularError{season.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SeasonQuery) OnlyX(ctx context.Context) *Season {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Season ID in the query.
// Returns a *NotSingularError when more than one Season ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SeasonQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{season.Label}
	default:
		err = &NotSingularError{season.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SeasonQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Seasons.
func (sq *SeasonQuery) All(ctx context.Context) ([]*Season, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryAll)
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Season, *SeasonQuery]()
	return withInterceptors[[]*Season](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SeasonQuery) AllX(ctx context.Context) []*Season {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Season IDs.
func (sq *SeasonQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryIDs)
	if err = sq.Select(season.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SeasonQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SeasonQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryCount)
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SeasonQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SeasonQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SeasonQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryExist)
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SeasonQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SeasonQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SeasonQuery) Clone() *SeasonQuery {
	if sq == nil {
		return nil
	}
	return &SeasonQuery{
		config:          sq.config,
		ctx:             sq.ctx.Clone(),
		order:           append([]season.OrderOption{}, sq.order...),
		inters:          append([]Interceptor{}, sq.inters...),
		predicates:      append([]predicate.Season{}, sq.predicates...),
		withBangumi:     sq.withBangumi.Clone(),
		withEpisodes:    sq.withEpisodes.Clone(),
		withCastMembers: sq.withCastMembers.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithBangumi tells the query-builder to eager-load the nodes that are connected to
// the "bangumi" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SeasonQuery) WithBangumi(opts ...func(*BangumiQuery)) *SeasonQuery {
	query := (&BangumiClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withBangumi = query
	return sq
}

// WithEpisodes tells the query-builder to eager-load the nodes that are connected to
// the "episodes" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SeasonQuery) WithEpisodes(opts ...func(*EpisodeQuery)) *SeasonQuery {
	query := (&EpisodeClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withEpisodes = query
	return sq
}

// WithCastMembers tells the query-builder to eager-load the nodes that are connected to
// the "cast_members" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SeasonQuery) WithCastMembers(opts ...func(*CastMemberQuery)) *SeasonQuery {
	query := (&CastMemberClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withCastMembers = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SeasonNumber int `json:"season_number,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Season.Query().
//		GroupBy(season.FieldSeasonNumber).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SeasonQuery) GroupBy(field string, fields ...string) *SeasonGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SeasonGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = season.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SeasonNumber int `json:"season_number,omitempty"`
//	}
//
//	client.Season.Query().
//		Select(season.FieldSeasonNumber).
//		Scan(ctx, &v)
func (sq *SeasonQuery) Select(fields ...string) *SeasonSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SeasonSelect{SeasonQuery: sq}
	sbuild.label = season.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SeasonSelect configured with the given aggregations.
func (sq *SeasonQuery) Aggregate(fns ...AggregateFunc) *SeasonSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SeasonQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !season.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SeasonQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Season, error) {
	var (
		nodes       = []*Season{}
		_spec       = sq.querySpec()
		loadedTypes = [3]bool{
			sq.withBangumi != nil,
			sq.withEpisodes != nil,
			sq.withCastMembers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Season).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Season{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withBangumi; query != nil {
		if err := sq.loadBangumi(ctx, query, nodes, nil,
			func(n *Season, e *Bangumi) { n.Edges.Bangumi = e }); err != nil {
			return nil, err
		}
	}
	if query := sq.withEpisodes; query != nil {
		if err := sq.loadEpisodes(ctx, query, nodes,
			func(n *Season) { n.Edges.Episodes = []*Episode{} },
			func(n *Season, e *Episode) { n.Edges.Episodes = append(n.Edges.Episodes, e) }); err != nil {
			return nil, err
		}
	}
	if query := sq.withCastMembers; query != nil {
		if err := sq.loadCastMembers(ctx, query, nodes,
			func(n *Season) { n.Edges.CastMembers = []*CastMember{} },
			func(n *Season, e *CastMember) { n.Edges.CastMembers = append(n.Edges.CastMembers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SeasonQuery) loadBangumi(ctx context.Context, query *BangumiQuery, nodes []*Season, init func(*Season), assign func(*Season, *Bangumi)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Season)
	for i := range nodes {
		fk := nodes[i].BangumiID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(bangumi.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bangumi_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (sq *SeasonQuery) loadEpisodes(ctx context.Context, query *EpisodeQuery, nodes []*Season, init func(*Season), assign func(*Season, *Episode)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Season)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(episode.FieldSeasonID)
	}
	query.Where(predicate.Episode(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(season.EpisodesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SeasonID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "season_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *SeasonQuery) loadCastMembers(ctx context.Context, query *CastMemberQuery, nodes []*Season, init func(*Season), assign func(*Season, *CastMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Season)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(castmember.FieldSeasonID)
	}
	query.Where(predicate.CastMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(season.CastMembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SeasonID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "season_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (sq *SeasonQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SeasonQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(season.Table, season.Columns, sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, season.FieldID)
		for i := range fields {
			if fields[i] != season.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if sq.withBangumi != nil {
			_spec.Node.AddColumnOnce(season.FieldBangumiID)
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SeasonQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(season.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = season.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SeasonGroupBy is the group-by builder for Season entities.
type SeasonGroupBy struct {
	selector
	build *SeasonQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SeasonGroupBy) Aggregate(fns ...AggregateFunc) *SeasonGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SeasonGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, ent.OpQueryGroupBy)
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SeasonQuery, *SeasonGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SeasonGroupBy) sqlScan(ctx context.Context, root *SeasonQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SeasonSelect is the builder for selecting fields of Season entities.
type SeasonSelect struct {
	*SeasonQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SeasonSelect) Aggregate(fns ...AggregateFunc) *SeasonSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SeasonSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, ent.OpQuerySelect)
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SeasonQuery, *SeasonSelect](ctx, ss.SeasonQuery, ss, ss.inters, v)
}

func (ss *SeasonSelect) sqlScan(ctx context.Context, root *SeasonQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
